name: my_portfolio
description: "My dev portfolio."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  change_app_package_name: ^1.1.0

  # Icons
  flutter_launcher_icons: ^0.13.1
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.5.0

  provider: ^6.0.5
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0
  url_launcher: ^6.2.1
  flutter_flip_card: ^0.0.4
  flutter_spinkit: ^5.2.0
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/images/development/
    - assets/images/projects/
    - assets/images/projects/compose/
    - assets/images/projects/flutter/
    - assets/images/projects/react/
    - assets/images/projects/xml/
    - assets/pdf/

  fonts:
    - family: CustomFont
      fonts:
        - asset: assets/fonts/montserrat.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
